[Service]
Host = "localhost"
Port = 6789

[Clients]
    [Clients.CoreData]
    Protocol = 'http'
    Host = '47.102.192.194'
    Port = 48080
    PathPrefix = "/core-data"

    [Clients.Metadata]
    Protocol = 'http'
    Host = '47.102.192.194'
    Port = 48081
    PathPrefix = "/core-metadata"

    [Clients.CoreCommand]
    Protocol = 'http'
    Host = '47.102.192.194'
    Port = 48082
    PathPrefix = "/core-command"

    [Clients.Notification]
    Protocol = 'http'
    Host = '47.102.192.194'
    Port = 48060
    PathPrefix = "/support-notification"

    [Clients.Scheduler]
    Protocol = 'http'
    Host = '47.102.192.194'
    Port = 48085
    PathPrefix = "/support-scheduler"

    [Clients.RuleEngine]
    Protocol = 'http'
    Host = '47.102.192.194'
    Port = 48075
    PathPrefix = "/rule-engine"

    [Clients.CoreExport]
    Protocol = 'http'
    Host = '47.102.192.194'
    Port = 48071
    PathPrefix = "/core-export"

    [Clients.System]
    Protocol = 'http'
    Host = '47.102.192.194'
    Port = 48090
    PathPrefix = "/system"
