[Service]
Host = "edgex-api"
Port = 6789

[Clients]
    [Clients.CoreData]
    Protocol = 'http'
    Host = 'edgex-core-data'
    Port = 48080
    PathPrefix = "/core-data"

    [Clients.Metadata]
    Protocol = 'http'
    Host = 'edgex-core-metadata'
    Port = 48081
    PathPrefix = "/core-metadata"

    [Clients.CoreCommand]
    Protocol = 'http'
    Host = 'edgex-core-command'
    Port = 48082
    PathPrefix = "/core-command"

    [Clients.Notification]
    Protocol = 'http'
    Host = 'edgex-support-notifications'
    Port = 48060
    PathPrefix = "/support-notification"

    [Clients.Scheduler]
    Protocol = 'http'
    Host = 'edgex-support-scheduler'
    Port = 48085
    PathPrefix = "/support-scheduler"

    [Clients.RuleEngine]
    Protocol = 'http'
    Host = 'edgex-kuiper'
    Port = 48075
    PathPrefix = "/rule-engine"

    [Clients.CoreExport]
    Protocol = 'http'
    Host = 'edgex-core-export'
    Port = 48071
    PathPrefix = "/core-export"

[Registry]
Host = "edgex-core-consul"
Port = 8500
Type = "consul"
ConfigRegistryStem="edgex/appservices/"
ServiceVersion="1.0"